apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "wx-jyy"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "wx-jyy"
    spec:
      containers:
        - name: "wx-jyy"
          image: "haicr.azurecr.io/k8s"
          ports:
          - containerPort: 80