apiVersion : apps/v1
kind: Deployment
metadata:
  name: "wx-jyy"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "wx-jyy"
    spec:
      containers:
        - name: "wx-jyy"
          image: "beacr.azurecr.io/wx-jyy"
          ports:
          - containerPort: 80