apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: ingress-wx-jyy
spec:
  rules:
    - host: www.wx-jyy.com
      http:
        paths:
          - backend:
              serviceName: wx-jyy
              servicePort: 80
            path: /
    - host: wx-jyy.com
      http:
        paths:
          - backend:
              serviceName: wx-jyy
              servicePort: 80
            path: /
  tls:
    - hosts:
        - www.wx-jyy.com
        - wx-jyy.com
      secretName: wx-jyy-tls
