apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: ingress-wx-jyy
spec:
  rules:
    - host: wx-jyy.ca34fb964e954c01a594.southeastasia.aksapp.io
      http:
        paths:
          - backend:
              serviceName: wx-jyy
              servicePort: 80
            path: /
  tls:
    - hosts:
        - wx-jyy.ca34fb964e954c01a594.southeastasia.aksapp.io
      secretName: wx-jyy-tls
