apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "k8s"
    labels:
        app: "k8s"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: k8s2fab-k8s.ca34fb964e954c01a594.southeastasia.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "k8s"
                servicePort: 80