apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wx-jyy-db
  namespace: wx-jyy
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: managed-csi
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wx-jyy-uploads
  namespace: wx-jyy
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: managed-csi
  resources:
    requests:
      storage: 4Gi
